# infrastructure/backend.tf
terraform {
  required_version = ">= 1.10"

  # Backend config is injected at init time via
  #   terraform init -backend-config=bootstrap/backend.hcl
  # That file is generated by the bootstrap stack's `backend_hcl` output
  # and committed after the first successful bootstrap.
  backend "s3" {}
}
